//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using Controller;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Model;
	public class Cuenta
	{
		private float interesGanado
		{
			get;
			set;
		}

		private float interesAnual
		{
			get;
			set;
		}

		private Moneda moneda
		{
			get;
			set;
		}

		private int periodo
		{
			get;
			set;
		}

		private float monto
		{
			get;
			set;
		}

		private TipoCuenta tipoCuenta
		{
			get;
			set;
		}

		private string nombre
		{
			get;
			set;
		}

		public virtual AdministradorOperaciones AdministradorOperaciones
		{
			get;
			set;
		}

		public virtual ICuenta ICuenta
		{
			get;
			set;
		}

		public Cuenta()
		{
		}

		public Cuenta(string nombre, TipoCuenta tipoCuenta, float monto, int periodo, Moneda moneda, float interesAnual, float interesGanado)
		{
		}

		public virtual void calcularTotal()
		{
			throw new System.NotImplementedException();
		}

	}
}

