//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modelo
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CuentaPlazo : Cuenta
	{

        public CuentaPlazo(string nombre, TipoCuenta tipoCuenta, float monto, int periodo, Moneda moneda)
        {
            base.Nombre = nombre;
            base.TipoCuenta = tipoCuenta;
            base.Monto = monto;
            base.Periodo = periodo;
            base.Moneda = moneda;
            base.InteresAnual = obtenerInteresAnual();
            base.InteresGanado = calcularInteresGanado();
        }

        override
        public float calcularInteresGanado()
        {
            float interes = base.Monto * base.InteresAnual;
            return interes;
        }

        override  //falta obtener el valor de la tabla
        public float obtenerInteresAnual()
        {
            float interes = 0; //Llamar aca funcion de andres
            return interes;
        }


        public float calcularRetencion()
        {
            double porcentaje = 0.08;   //se implementa de esta manera ya que sera mas simple por las divisiones entre 0
            float retencion = base.Monto * (float)porcentaje;
            return retencion;
        }

        override
        public float calcularTotal()
        {
            float total = base.Monto + base.InteresGanado - calcularRetencion();
            return total;
        }
    }
}

