//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modelo
{
    using Modelo;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;


    public class InteresCorriente : ICuenta
	{
        public IObtenerTablaAPI IObtenerTablaAPI
        {
            get; set;
        }

        public virtual float buscarInteres(float monto,Moneda moneda)
		{

            ObtenerTablaInteresCorrienteCSV tablaParaApi = new ObtenerTablaInteresCorrienteCSV();
            IObtenerTablaAPI = tablaParaApi;
            SortedDictionary<float, float> tabla = IObtenerTablaAPI.ObtenerTabla(moneda);
            float interes = tabla.FloorEntry(monto).Value;
            return interes;

        }

	}
}

