//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modelo
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using Modelo;

    public abstract class ObtenerTablaCSV : IObtenerTablaAPI
	{
        

        public abstract StreamReader ObtenerDatosCSV();

        public abstract SortedDictionary<float, float> ObtenerTabla(Moneda moneda);
    }
}

