//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using ProyectoIDiseno.Controller;
    using Modelo;

    public class ControladorViews
	{
        private static AdministradorOperaciones pAdministradorDeOperaciones;
        private static Modelo.Moneda mmoneda=new  Moneda();
        private static Modelo.TipoCuenta ttipoCuenta = new TipoCuenta();
        private static ContextCuenta contextCuenta;
        public static String creaCuenta(String nombre,String tipoCuenta,float monto,int periodo,String moneda) {
            
            if (esNombreValido(nombre) && esMonedaValida(moneda) && esTipoCuentaValido(tipoCuenta))
            {
                if (!contextCuenta.executeStrategyRevisarMin(monto, periodo, mmoneda))
                {
                    return "La cuenta no cumple con las condiciones!";
                }
                else
                {
                    Cuenta cuenta= contextCuenta.executeCrearCuenta(nombre, ttipoCuenta, monto, periodo, mmoneda);
                    return cuenta.toString();
                }
            }
            else {
                return "Por favor verifique los datos!";
            }
        }
        private static bool esNombreValido(String nombre)
        {
            if (nombre == "" || nombre == null)
            {
                return false;
            }
            else {
                return true;
            }
        }
        private static bool esTipoCuentaValido(String tipoCuenta)
        {
            if (tipoCuenta == "corriente" )
            {
                ttipoCuenta = TipoCuenta.Corriente;
                contextCuenta= new ContextCuenta(new OperacionesCCorriente());
                return true;
            }
            if (tipoCuenta == "pactada")
            {
                contextCuenta = new ContextCuenta(new OperacionTPactado());
                ttipoCuenta = TipoCuenta.Pactada;
                return true;
            }
            if (tipoCuenta == "certificado")
            {
                contextCuenta = new ContextCuenta(new OperacionesPlazo());
                ttipoCuenta = TipoCuenta.Plazo;
                return true;
            }
            else
            {
                return false;
            }
        }

        private static bool esMonedaValida(String tipoCuenta)
        {
            if (tipoCuenta == "colon" )
            {
                mmoneda=Moneda.Colon;
                return true;
            }
            
            if (tipoCuenta == "dolar")
            {
                mmoneda = Moneda.Dolar;
                return true;
            }
            else
            {
                return false;
            }
        }



    }
}

