//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Modelo;
    using ProyectoIDiseno.Controller;

    public class OperacionesCCorriente : AdministradorOperaciones
	{

        private static int MONTO_MIN = 25000;

        private CuentaFactory cuentaFactory = new CuentaFactory();

        public Cuenta crearCuenta(TipoCuenta pTipo)
        {
            throw new NotImplementedException();
        }

        public Cuenta crearCuenta(String pNombre, TipoCuenta pTipoCuenta, float pMonto, int pPeriodo, Moneda pMoneda)
        {
            return cuentaFactory.getCuenta(pNombre, pTipoCuenta, pMonto, pPeriodo, pMoneda);
        }

        public virtual bool revisarMinimo(float pMonto, int pDias, Moneda pMoneda)
		{
            if (pMonto >= MONTO_MIN)
            {
                if (pMoneda == Moneda.Colon)
                    return true;
                else {
                    Console.WriteLine("Error: Para crear una cuenta corrienta su tipo de moneda debe de ser colones");
                    return false;
                   
                }
            }
            else {
                Console.WriteLine("Error: No dispone de suficiente saldo para crear la cuenta corriente");
                return false;
            }
        }

        public bool revisarMinimo(string pNombre, TipoCuenta pTipoCuenta, float pMonto, int pPeriodo, Moneda pMoneda)
        {
            throw new NotImplementedException();
        }
    }
}

