//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OperacionesPlazo
	{
		private int diasMinimo
		{
			get;
			set;
		}

		public virtual AdministradorOperaciones AdministradorOperaciones
		{
			get;
			set;
		}

		public virtual float retencionImpuestos()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool revisarMinimo()
		{
			throw new System.NotImplementedException();
		}

	}
}

