//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Model;

	public class OperacionTPactado
	{
		private int diasMinino
		{
			get;
			set;
		}

		private float montoMinimo
		{
			get;
			set;
		}

		private Moneda moneda
		{
			get;
			set;
		}

		public virtual AdministradorOperaciones AdministradorOperaciones
		{
			get;
			set;
		}

		public virtual float retencionImpuestos()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool revisarMinimo()
		{
			throw new System.NotImplementedException();
		}

	}
}

