//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Model;

    public class XML : ManejoArchivos
	{
        public override bool escribirArchivo(Cuenta cuenta)
        {
            throw new NotImplementedException();
        }

     

	}
}

